from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from symgene.llm.client import LLMClient

_SYSTEM = """\
You are an expert in mathematical physics and scientific machine learning.
Your task is to interpret symbolic expressions discovered by a genetic programming
algorithm, explaining their physical meaning in the context of the described domain.
Be concise, specific, and focus on physical insight rather than restating the formula."""

_USER = """\
A Multi-Gene Genetic Programming (MGGP) model was fitted for the following problem:

Domain: {description}
Target variable: {target_name}
Input variables: {feature_names}

The model is a weighted sum of {n_genes} gene(s):

    ŷ = w₁·g₁(x) + w₂·g₂(x) + ... + wₙ·gₙ(x)

Genes and their weights (sorted by absolute importance):
{genes_with_weights}

Full expression (LaTeX):
    {latex}

Please provide a physical interpretation covering:
1. What each gene (term) likely represents in the physical context.
2. Whether the overall mathematical structure is consistent with known theory.
3. Any surprising, unexpected, or physically meaningful features of the expression.

If the domain description is insufficient to give a detailed interpretation,
state what additional context would help."""


def _format_genes_with_weights(
    latex_expr: str,
    coefficients: object,
    n_genes: int,
) -> str:
    try:
        import numpy as np
        coef = np.asarray(coefficients).ravel()
        pairs = sorted(
            enumerate(coef, start=1),
            key=lambda kv: abs(kv[1]),
            reverse=True,
        )
        lines = [f"  Gene {i}: weight = {w:+.4f}" for i, w in pairs]
        return "\n".join(lines)
    except Exception:
        return f"  (weights unavailable — {n_genes} gene(s) total)"


def interpret_population(
    latex: str,
    description: str,
    target_name: str,
    feature_names: list[str],
    n_genes: int,
    coefficients: object,
    client: "LLMClient",
) -> str:
    """Ask an LLM to physically interpret a MGGP symbolic expression.

    Parameters
    ----------
    latex : str
        LaTeX string of the fitted expression from ``to_latex()``.
    description : str
        Natural-language description of the modeled phenomenon.
    target_name : str
        Name of the target variable (e.g. ``"PPF"``).
    feature_names : list of str
        Domain names of the input variables.
    n_genes : int
        Number of genes in the best individual.
    coefficients : array-like or None
        Ridge/Lasso coefficients for the genes.
    client : LLMClient
        Configured LLM client.

    Returns
    -------
    str
        Physical interpretation generated by the LLM.
    """
    genes_block = _format_genes_with_weights(latex, coefficients, n_genes)
    feat_str = ", ".join(feature_names) if feature_names else "not provided"

    prompt = _USER.format(
        description=description,
        target_name=target_name,
        feature_names=feat_str,
        n_genes=n_genes,
        genes_with_weights=genes_block,
        latex=latex if latex else "(symbolic export not available)",
    )

    return client.complete(prompt=prompt, system=_SYSTEM)
